// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'edition.dart';

// **************************************************************************
// SchemaGenerator
// **************************************************************************

/// Prose for one edition, generated by the LLM. Repo metadata is held in
/// code (the Selection); this schema carries prose only.
base class Edition {
  /// Creates a [Edition] from a JSON map.
  factory Edition.fromJson(Map<String, dynamic> json) => $schema.parse(json);

  Edition._(this._json);

  Edition({
    required String title,
    required String intro,
    required MainContent main,
    required List<SubContent> subs,
  }) {
    _json = {
      'title': title,
      'intro': intro,
      'main': main.toJson(),
      'subs': subs.map((e) => e.toJson()).toList(),
    };
  }

  late final Map<String, dynamic> _json;

  /// The JSON schema and type descriptor for [Edition].
  static const SchemanticType<Edition> $schema = _EditionTypeFactory();

  /// Edition title (Japanese, ~20-40 chars).
  String get title {
    return _json['title'] as String;
  }

  /// Edition title (Japanese, ~20-40 chars).
  set title(String value) {
    _json['title'] = value;
  }

  /// Intro: 1-2 sentences framing the day's edition.
  String get intro {
    return _json['intro'] as String;
  }

  /// Intro: 1-2 sentences framing the day's edition.
  set intro(String value) {
    _json['intro'] = value;
  }

  /// The main deep-dive content.
  MainContent get main {
    return MainContent.fromJson(_json['main'] as Map<String, dynamic>);
  }

  /// The main deep-dive content.
  set main(MainContent value) {
    _json['main'] = value.toJson();
  }

  /// New-arrival sub items (same order and count as the selected subs).
  List<SubContent> get subs {
    return (_json['subs'] as List)
        .map((e) => SubContent.fromJson(e as Map<String, dynamic>))
        .toList();
  }

  /// New-arrival sub items (same order and count as the selected subs).
  set subs(List<SubContent> value) {
    _json['subs'] = value.map((e) => e.toJson()).toList();
  }

  @override
  String toString() {
    return _json.toString();
  }

  /// Serializes this [Edition] to a JSON map.
  Map<String, dynamic> toJson() {
    return _json;
  }
}

base class _EditionTypeFactory extends SchemanticType<Edition> {
  const _EditionTypeFactory();

  @override
  Edition parse(Object? json) {
    return Edition._(json as Map<String, dynamic>);
  }

  @override
  JsonSchemaMetadata get schemaMetadata => JsonSchemaMetadata(
    name: 'Edition',
    definition: $Schema
        .object(
          properties: {
            'title': $Schema.string(),
            'intro': $Schema.string(),
            'main': $Schema.fromMap({'\$ref': r'#/$defs/MainContent'}),
            'subs': $Schema.list(
              items: $Schema.fromMap({'\$ref': r'#/$defs/SubContent'}),
            ),
          },
          required: ['title', 'intro', 'main', 'subs'],
        )
        .value,
    dependencies: [MainContent.$schema, SubContent.$schema],
  );
}

base class MainContent {
  /// Creates a [MainContent] from a JSON map.
  factory MainContent.fromJson(Map<String, dynamic> json) =>
      $schema.parse(json);

  MainContent._(this._json);

  MainContent({
    required String hook,
    required String whatItIs,
    required String whyItResonates,
    required List<String> useCases,
    required String firstStep,
  }) {
    _json = {
      'hook': hook,
      'whatItIs': whatItIs,
      'whyItResonates': whyItResonates,
      'useCases': useCases,
      'firstStep': firstStep,
    };
  }

  late final Map<String, dynamic> _json;

  /// The JSON schema and type descriptor for [MainContent].
  static const SchemanticType<MainContent> $schema = _MainContentTypeFactory();

  /// One-line hook.
  String get hook {
    return _json['hook'] as String;
  }

  /// One-line hook.
  set hook(String value) {
    _json['hook'] = value;
  }

  /// What it is.
  String get whatItIs {
    return _json['whatItIs'] as String;
  }

  /// What it is.
  set whatItIs(String value) {
    _json['whatItIs'] = value;
  }

  /// Why it resonates / its connection to the author's stack.
  String get whyItResonates {
    return _json['whyItResonates'] as String;
  }

  /// Why it resonates / its connection to the author's stack.
  set whyItResonates(String value) {
    _json['whyItResonates'] = value;
  }

  /// Concrete use cases (2-3 items).
  List<String> get useCases {
    return (_json['useCases'] as List).cast<String>();
  }

  /// Concrete use cases (2-3 items).
  set useCases(List<String> value) {
    _json['useCases'] = value;
  }

  /// A first step to try it.
  String get firstStep {
    return _json['firstStep'] as String;
  }

  /// A first step to try it.
  set firstStep(String value) {
    _json['firstStep'] = value;
  }

  @override
  String toString() {
    return _json.toString();
  }

  /// Serializes this [MainContent] to a JSON map.
  Map<String, dynamic> toJson() {
    return _json;
  }
}

base class _MainContentTypeFactory extends SchemanticType<MainContent> {
  const _MainContentTypeFactory();

  @override
  MainContent parse(Object? json) {
    return MainContent._(json as Map<String, dynamic>);
  }

  @override
  JsonSchemaMetadata get schemaMetadata => JsonSchemaMetadata(
    name: 'MainContent',
    definition: $Schema
        .object(
          properties: {
            'hook': $Schema.string(),
            'whatItIs': $Schema.string(),
            'whyItResonates': $Schema.string(),
            'useCases': $Schema.list(items: $Schema.string()),
            'firstStep': $Schema.string(),
          },
          required: [
            'hook',
            'whatItIs',
            'whyItResonates',
            'useCases',
            'firstStep',
          ],
        )
        .value,
    dependencies: [],
  );
}

base class SubContent {
  /// Creates a [SubContent] from a JSON map.
  factory SubContent.fromJson(Map<String, dynamic> json) => $schema.parse(json);

  SubContent._(this._json);

  SubContent({required String oneLine, required String hook}) {
    _json = {'oneLine': oneLine, 'hook': hook};
  }

  late final Map<String, dynamic> _json;

  /// The JSON schema and type descriptor for [SubContent].
  static const SchemanticType<SubContent> $schema = _SubContentTypeFactory();

  /// One line: what it is.
  String get oneLine {
    return _json['oneLine'] as String;
  }

  /// One line: what it is.
  set oneLine(String value) {
    _json['oneLine'] = value;
  }

  /// One line: how it could be useful.
  String get hook {
    return _json['hook'] as String;
  }

  /// One line: how it could be useful.
  set hook(String value) {
    _json['hook'] = value;
  }

  @override
  String toString() {
    return _json.toString();
  }

  /// Serializes this [SubContent] to a JSON map.
  Map<String, dynamic> toJson() {
    return _json;
  }
}

base class _SubContentTypeFactory extends SchemanticType<SubContent> {
  const _SubContentTypeFactory();

  @override
  SubContent parse(Object? json) {
    return SubContent._(json as Map<String, dynamic>);
  }

  @override
  JsonSchemaMetadata get schemaMetadata => JsonSchemaMetadata(
    name: 'SubContent',
    definition: $Schema
        .object(
          properties: {'oneLine': $Schema.string(), 'hook': $Schema.string()},
          required: ['oneLine', 'hook'],
        )
        .value,
    dependencies: [],
  );
}

/// Authoritative repo metadata for an edition (from the Selection, not the LLM).
base class RepoRef {
  /// Creates a [RepoRef] from a JSON map.
  factory RepoRef.fromJson(Map<String, dynamic> json) => $schema.parse(json);

  RepoRef._(this._json);

  RepoRef({
    required String id,
    required String url,
    required String category,
    String? language,
    int? stars,
  }) {
    _json = {
      'id': id,
      'url': url,
      'category': category,
      'language': ?language,
      'stars': ?stars,
    };
  }

  late final Map<String, dynamic> _json;

  /// The JSON schema and type descriptor for [RepoRef].
  static const SchemanticType<RepoRef> $schema = _RepoRefTypeFactory();

  String get id {
    return _json['id'] as String;
  }

  set id(String value) {
    _json['id'] = value;
  }

  String get url {
    return _json['url'] as String;
  }

  set url(String value) {
    _json['url'] = value;
  }

  String get category {
    return _json['category'] as String;
  }

  set category(String value) {
    _json['category'] = value;
  }

  String? get language {
    return _json['language'] as String?;
  }

  set language(String? value) {
    if (value == null) {
      _json.remove('language');
    } else {
      _json['language'] = value;
    }
  }

  int? get stars {
    return _json['stars'] as int?;
  }

  set stars(int? value) {
    if (value == null) {
      _json.remove('stars');
    } else {
      _json['stars'] = value;
    }
  }

  @override
  String toString() {
    return _json.toString();
  }

  /// Serializes this [RepoRef] to a JSON map.
  Map<String, dynamic> toJson() {
    return _json;
  }
}

base class _RepoRefTypeFactory extends SchemanticType<RepoRef> {
  const _RepoRefTypeFactory();

  @override
  RepoRef parse(Object? json) {
    return RepoRef._(json as Map<String, dynamic>);
  }

  @override
  JsonSchemaMetadata get schemaMetadata => JsonSchemaMetadata(
    name: 'RepoRef',
    definition: $Schema
        .object(
          properties: {
            'id': $Schema.string(),
            'url': $Schema.string(),
            'category': $Schema.string(),
            'language': $Schema.string(),
            'stars': $Schema.integer(),
          },
          required: ['id', 'url', 'category'],
        )
        .value,
    dependencies: [],
  );
}

/// The full result of the generation flow: LLM prose + the selected repos.
base class DigestResult {
  /// Creates a [DigestResult] from a JSON map.
  factory DigestResult.fromJson(Map<String, dynamic> json) =>
      $schema.parse(json);

  DigestResult._(this._json);

  DigestResult({
    required String dateJst,
    required Edition edition,
    required RepoRef main,
    required List<RepoRef> subs,
    required List<RepoRef> overflow,
  }) {
    _json = {
      'dateJst': dateJst,
      'edition': edition.toJson(),
      'main': main.toJson(),
      'subs': subs.map((e) => e.toJson()).toList(),
      'overflow': overflow.map((e) => e.toJson()).toList(),
    };
  }

  late final Map<String, dynamic> _json;

  /// The JSON schema and type descriptor for [DigestResult].
  static const SchemanticType<DigestResult> $schema =
      _DigestResultTypeFactory();

  String get dateJst {
    return _json['dateJst'] as String;
  }

  set dateJst(String value) {
    _json['dateJst'] = value;
  }

  Edition get edition {
    return Edition.fromJson(_json['edition'] as Map<String, dynamic>);
  }

  set edition(Edition value) {
    _json['edition'] = value.toJson();
  }

  RepoRef get main {
    return RepoRef.fromJson(_json['main'] as Map<String, dynamic>);
  }

  set main(RepoRef value) {
    _json['main'] = value.toJson();
  }

  List<RepoRef> get subs {
    return (_json['subs'] as List)
        .map((e) => RepoRef.fromJson(e as Map<String, dynamic>))
        .toList();
  }

  set subs(List<RepoRef> value) {
    _json['subs'] = value.map((e) => e.toJson()).toList();
  }

  List<RepoRef> get overflow {
    return (_json['overflow'] as List)
        .map((e) => RepoRef.fromJson(e as Map<String, dynamic>))
        .toList();
  }

  set overflow(List<RepoRef> value) {
    _json['overflow'] = value.map((e) => e.toJson()).toList();
  }

  @override
  String toString() {
    return _json.toString();
  }

  /// Serializes this [DigestResult] to a JSON map.
  Map<String, dynamic> toJson() {
    return _json;
  }
}

base class _DigestResultTypeFactory extends SchemanticType<DigestResult> {
  const _DigestResultTypeFactory();

  @override
  DigestResult parse(Object? json) {
    return DigestResult._(json as Map<String, dynamic>);
  }

  @override
  JsonSchemaMetadata get schemaMetadata => JsonSchemaMetadata(
    name: 'DigestResult',
    definition: $Schema
        .object(
          properties: {
            'dateJst': $Schema.string(),
            'edition': $Schema.fromMap({'\$ref': r'#/$defs/Edition'}),
            'main': $Schema.fromMap({'\$ref': r'#/$defs/RepoRef'}),
            'subs': $Schema.list(
              items: $Schema.fromMap({'\$ref': r'#/$defs/RepoRef'}),
            ),
            'overflow': $Schema.list(
              items: $Schema.fromMap({'\$ref': r'#/$defs/RepoRef'}),
            ),
          },
          required: ['dateJst', 'edition', 'main', 'subs', 'overflow'],
        )
        .value,
    dependencies: [Edition.$schema, RepoRef.$schema],
  );
}
