import 'package:schemantic/schemantic.dart';

part 'edition.g.dart';

/// Prose for one edition, generated by the LLM. Repo metadata is held in
/// code (the Selection); this schema carries prose only.
@Schema()
abstract class $Edition {
  /// Edition title (Japanese, ~20-40 chars).
  String get title;

  /// Intro: 1-2 sentences framing the day's edition.
  String get intro;

  /// The main deep-dive content.
  $MainContent get main;

  /// New-arrival sub items (same order and count as the selected subs).
  List<$SubContent> get subs;
}

@Schema()
abstract class $MainContent {
  /// One-line hook.
  String get hook;

  /// What it is.
  String get whatItIs;

  /// Why it resonates / its connection to the author's stack.
  String get whyItResonates;

  /// Concrete use cases (2-3 items).
  List<String> get useCases;

  /// A first step to try it.
  String get firstStep;
}

@Schema()
abstract class $SubContent {
  /// One line: what it is.
  String get oneLine;

  /// One line: how it could be useful.
  String get hook;
}

/// Authoritative repo metadata for an edition (from the Selection, not the LLM).
@Schema()
abstract class $RepoRef {
  String get id;
  String get url;
  String get category;
  String? get language;
  int? get stars;
}

/// The full result of the generation flow: LLM prose + the selected repos.
@Schema()
abstract class $DigestResult {
  String get dateJst;
  $Edition get edition;
  $RepoRef get main;
  List<$RepoRef> get subs;
  List<$RepoRef> get overflow;
}
